<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>VideoWall.Master</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.59.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoWall.Core\VideoWall.Core.csproj" />
    <ProjectReference Include="..\VideoWall.Network\VideoWall.Network.csproj" />
    <ProjectReference Include="..\VideoWall.Transitions\VideoWall.Transitions.csproj" />
  </ItemGroup>

</Project>
